#!/bin/bash

PROJ=mpservice
SRC=$(pwd)/src/${PROJ}
TESTS=$(pwd)/tests


echo
echo --- running bandit ---
echo
bandit -r -lll ${SRC} || exit 1
bandit -r -lll ${TESTS} || exit 1

echo
echo --- running pyflakes ---
echo
python -m pyflakes ${SRC} || exit 1
echo
python -m pyflakes ${TESTS} || exit 1

echo
echo --- running mypy ---
echo
python -m mypy ${SRC}

echo
echo --- running pylint ---
echo
python -m pylint --disable=C0103,C0114,C0115,C0116,C0301,C0303,C0305,R0903 ${SRC}

exit 0
